### ISSUE TITLE
오타 제보합니다.

### ISSUE THREAD

**Issue by CHANMYUNG** [jojoldu/review#2]
README.md 파일 최상단에 
'기' 라는 오타가 있네요!

PR하기엔 너무 약소해서 이슈 남깁니다.
올려주시는 자료들 잘 보고 있어요 😀 감사합니다.

**Comment by jojoldu** [comment]
아고 감사합니다 ㅠ ㅋㅋ 
바로 수정했습니다!

**Comment by CHANMYUNG** [comment]
올려주시는 자료들 잘 보고 있어요 😄 
스프링부트로 웹 서비스 구축하기랑.. 주니어 개발자 취업 자료 등등 항상 감사합니다 😁

**Comment by jojoldu** [comment]
@Nooheat 아고 감사합니다 ㅎㅎㅎ 앞으로도 잘 부탁드릴게요! :)
